#ifndef LEDWALLSTUDIO_SIMULATOR_SUPPORT_ESP_LOG_H
#define LEDWALLSTUDIO_SIMULATOR_SUPPORT_ESP_LOG_H

#define ESP_LOGD
#define ESP_LOGI
#define ESP_LOGE

#endif //LEDWALLSTUDIO_SIMULATOR_SUPPORT_ESP_LOG_H
